Mock-exams/01-Mock-exam/expensesTracker/expensesTracker/app/urls.py
from django.urls import path

from expensesTracker.app.views import home, create, edit, delete, profile, profile_edit, profile_delete

urlpatterns = [
    path('', home, name='home'),
    path('create/', create, name='create'),
    path('edit/<int:pk>', edit, name='edit'),
    path('delete/<int:pk>', delete, name='delete'),
    path('profile/', profile, name='profile'),
    path('profile/edit', profile_edit, name='profile edit'),
    path('profile/delete', profile_delete, name='profile delete'),
]

Mock-exams/01-Mock-exam/expensesTracker/expensesTracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expensesTracker.app.urls'))
]

Mock-exams/01-Mock-exam/expensesTracker/expensesTracker/app/models.py
from django.db import models


class Profile(models.Model):
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=15)
    budget = models.IntegerField()


class Expense(models.Model):
    title = models.CharField(max_length=50)
    image_url = models.URLField()
    description = models.TextField()
    price = models.FloatField()

Mock-exams/01-Mock-exam/expensesTracker/expensesTracker/app/forms.py
from django import forms

from expensesTracker.app.models import Profile, Expense


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'


class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = '__all__'

Mock-exams/01-Mock-exam/expensesTracker/expensesTracker/app/views.py
from django.shortcuts import render, redirect

from expensesTracker.app.forms import ProfileForm, ExpenseForm
from expensesTracker.app.models import Profile, Expense


def home(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
        else:
            return render(request, 'home-no-profile.html', {'form': form})
    else:
        profile = Profile.objects.all()
        if profile:
            profile = Profile.objects.all()[0]
            expenses = Expense.objects.all()
            cash_left = profile.budget - sum([expense.price for expense in expenses])
            return render(request, 'home-with-profile.html',
                          {'profile': profile, 'expenses': expenses, 'cash_left': cash_left})
        else:
            return render(request, 'home-no-profile.html')


def create(request):
    if request.method == 'POST':
        form = ExpenseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        return render(request, 'expense-create.html')


def edit(request, pk):
    expense = Expense.objects.get(pk=pk)
    if request.method == 'POST':
        form = ExpenseForm(request.POST, instance=expense)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        return render(request, 'expense-edit.html', {'expense': expense})


def delete(request, pk):
    expense = Expense.objects.get(pk=pk)
    if request.method == 'POST':
        expense.delete()
        return redirect('home')
    else:
        return render(request, 'expense-delete.html', {'expense': expense})


def profile(request):
    profile = Profile.objects.all()[0]
    expenses = Expense.objects.all()
    budget = profile.budget - sum([expense.price for expense in expenses])
    return render(request, 'profile.html', {'profile': profile, 'budget': budget})


def profile_edit(request):
    profile = Profile.objects.all()[0]
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        return render(request, 'profile-edit.html', {'profile': profile})


def profile_delete(request):
    profile = Profile.objects.all()[0]
    if request.method == 'POST':
        profile.delete()
        expenses = Expense.objects.all()
        expenses.delete()
        return redirect('home')
    else:
        return render(request, 'profile-delete.html')

Mock-exams/01-Mock-exam/expensesTracker/templates/expense-create.html
{% load static %}
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="{% static 'images/dollar.png'%}"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Create Expense</h1>
<div class="form">
    <form method="POST">
        {% csrf_token %}
        <label for="name">Title</label>
        <input type="text" name="title" maxlength="50" required="" id="id_title">

        <label for="description">Description</label>
        <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>

        <label for="imageUrl">Link to Image</label>
        <input type="url" name="image_url" maxlength="200" required="" id="id_image_url">

        <label for="price">Price</label>
        <input type="number" name="price" step="any" required="" id="id_price">

        <input type="submit" value="Create">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

Mock-exams/01-Mock-exam/expensesTracker/templates/expense-delete.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Expenses Tracker</title>
</head>

<body>

<nav>
    <ul>
        <li class="img"><img src="{% static 'images/dollar.png' %}"></li>
        <li><a href="/">Expenses Tracker</a></li>

        <li class="right"><a href="/profile">Profile</a></li>

    </ul>
</nav>
<div class="body">

    <h1>Delete Expense</h1>
    <div class="form">
        <form method="POST">
            {% csrf_token %}
            <label for="name">Title</label>
            <input type="text" name="title" value="{{ expense.title }}" maxlength="50" disabled="" required=""
                   id="id_title">

            <label for="description">Description</label>
            <textarea name="description" cols="40" rows="10" disabled="" required=""
                      id="id_description">{{ expense.description }}</textarea>

            <label for="image_url">Link to Image</label>
            <input type="url" name="image_url"
                   value="{{ expense.image_url }}" maxlength="200"
                   disabled="" required="" id="id_image_url">

            <label for="price">Price</label>
            <input type="number" name="price" value="{{ expense.price }}" step="any" disabled="" required="" id="id_price">

            <input type="submit" value="Delete">
        </form>
    </div>

</div>
<footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body>
</html>

Mock-exams/01-Mock-exam/expensesTracker/templates/expense-edit.html
{% load static %}
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="{% static 'images/dollar.png'%}"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Edit Expense</h1>
<div class="form">
    <form method="POST">
        {% csrf_token %}
        <label for="name">Title</label>
        <input type="text" name="title" value="{{ expense.title }}" maxlength="50" required="" id="id_title">

        <label for="description">Description</label>
        <textarea name="description" cols="40" rows="10" required="" id="id_description">{{ expense.description}}</textarea>

        <label for="image_url">Link to Image</label>
        <input type="url" name="image_url" value="{{ expense.image_url}}" maxlength="200" required="" id="id_image_url">

        <label for="price">Price</label>
        <input type="number" name="price" value="{{ expense.price }}" step="any" required="" id="id_price">

        <input type="submit" value="Edit">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

Mock-exams/01-Mock-exam/expensesTracker/templates/home-no-profile.html
{% load static %}
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="{% static 'images/dollar.png'%}"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Enter your data</h1>
<div class="form">
    <form method="POST">
        {% csrf_token %}
        <label for="budget">Budget</label>
        <input type="number" name="budget" required="" id="id_budget">

        <label for="firstName">First Name</label>
        <input type="text" name="first_name" maxlength="15" required="" id="id_first_name">

        <label for="lastName">Last Name</label>
        <input type="text" name="last_name" maxlength="15" required="" id="id_last_name">

        <input type="submit" value="Submit">
    </form>
    {% if form %}
        <p>{{ form.errors }}</p>
    {% endif %}
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

Mock-exams/01-Mock-exam/expensesTracker/templates/home-with-profile.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
    <title>Expenses Tracker</title>
</head>

<body>

<nav>
    <ul>
        <li class="img"><img src="{% static 'images/dollar.png'%}"></li>
        <li><a href="/">Expenses Tracker</a></li>

        <li class="right"><a href="/profile">Profile</a></li>

    </ul>
</nav>
<div class="body">

    {% if expenses %}
        <div>
            <h1>Summary</h1>
            <h1>
                <ul class="expenses-list">
                    <li class="blue">{{ profile.budget }}$</li>
                    {% for expense in expenses %}
                        <li class="red"> - {{ expense.price }}$</li>
                    {% endfor %}

                    <li class="green">= {{ cash_left }}$ left</li>
                </ul>
            </h1>
        </div>
    {% endif %}

    <h1>My Expenses</h1>
    <a href="/create">Add Expense</a>

    {% if expenses %}
        <div class="expenses-container">
            {% for expense in expenses %}
                <div class="expense-container">
                    <h2>{{ expense.title }}</h2>
                    <hr>
                    <img src="{{ expense.image_url }}">
                    <p>{{ expense.description }}</p>
                    <div class="expense-detail">
                        <div>
                            <p>Price: {{ expense.price }}$</p>
                        </div>
                        <div class="right">
                            <a class="button edit" href="/edit/{{ expense.id }}">Edit</a>
                            <a class="button delete" href="/delete/{{ expense.id }}">Delete</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}

</div>
<footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body>
</html>

Mock-exams/01-Mock-exam/expensesTracker/templates/profile-delete.html
{% load static %}
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="{% static 'images/dollar.png' %}"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Are you sure you want to delete your profile?</h1>
<form method="POST">
{% csrf_token %}
<button class="delete">Confirm</button>
</form>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

Mock-exams/01-Mock-exam/expensesTracker/templates/profile-edit.html
{% load static %}
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="{% static 'images/dollar.png' %}"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Enter your new data</h1>
<div class="form">
    <form method="POST">
        {% csrf_token %}
        <label for="budget">Budget</label>
        <input type="number" name="budget" value="{{ profile.budget }}" required="" id="id_budget">

        <label for="firstName">First Name</label>
        <input type="text" name="first_name" value="{{ profile.first_name }}" maxlength="15" required="" id="id_first_name">

        <label for="lastName">Last Name</label>
        <input type="text" name="last_name" value="{{ profile.last_name }}" maxlength="15" required="" id="id_last_name">

        <input type="submit" value="Edit">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

Mock-exams/01-Mock-exam/expensesTracker/templates/profile.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Expenses Tracker</title>
</head>

<body>

<nav>
    <ul>
        <li class="img"><img src="{% static 'images/dollar.png' %}"></li>
        <li><a href="/">Expenses Tracker</a></li>

        <li class="right"><a href="/profile">Profile</a></li>

    </ul>
</nav>
<div class="body">

    <h1>Your Profile</h1>
    <div class="expenses-container">
        <div class="expense-container">
            <h2>{{ profile.first_name }} {{ profile.last_name }}</h2>
            <hr>
            <img src="{% static 'images/user.png' %}">
            <p>In your profile you can edit your profile data</p>
            <div class="expense-detail">
                <div>
                    <p>Budget Left: {{ budget }}$</p>
                </div>
                <div class="right">
                    <a class="button edit" href="/profile/edit">Edit Profile</a>
                    <a class="button delete" href="/profile/delete">Delete Profile</a>
                </div>
            </div>
        </div>
    </div>

</div>
<footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body>
</html>