Mock-exams/04-Mock-exam/recipes/recipes/app/urls.py
from django.urls import path

from recipes.app.views import show_home, create_recipe, edit_recipe, delete_recipe, recipe_details

urlpatterns = [
    path('', show_home, name='home'),
    path('create/', create_recipe, name='create recipe'),
    path('edit/<int:pk>', edit_recipe, name='edit recipe'),
    path('delete/<int:pk>', delete_recipe, name='delete recipe'),
    path('details/<int:pk>', recipe_details, name='recipe details'),
]

Mock-exams/04-Mock-exam/recipes/recipes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.app.urls'))
]

Mock-exams/04-Mock-exam/recipes/recipes/app/models.py
from django.db import models


class Recipe(models.Model):
    title = models.CharField(max_length=30)
    image_url = models.URLField()
    description = models.TextField()
    ingredients = models.CharField(max_length=250)
    time = models.IntegerField()

Mock-exams/04-Mock-exam/recipes/recipes/app/forms.py
from django import forms

from recipes.app.models import Recipe


class RecipeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        kwargs['label_suffix'] = ''
        super().__init__(*args, **kwargs)

    class Meta:
        model = Recipe
        fields = '__all__'
        labels = {
            'title': 'Title',
            'image_url': 'Image URL',
            'description': 'Description',
            'ingredients': 'Ingredients',
            'time': 'Time (Minutes)',
        }


class DeleteRecipeForm(RecipeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs['disabled'] = 'disabled'

Mock-exams/04-Mock-exam/recipes/recipes/app/views.py
from django.shortcuts import render, redirect

from recipes.app.forms import RecipeForm, DeleteRecipeForm
from recipes.app.models import Recipe


def show_home(request):
    recipes = Recipe.objects.all()
    return render(request, 'index.html', {'recipes': recipes})


def create_recipe(request):
    if request.method == 'GET':
        form = RecipeForm()
        return render(request, 'create.html', {'form': form})
    else:
        form = RecipeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
        else:
            return render(request, 'create.html', {'form': form})


def edit_recipe(request, pk):
    recipe = Recipe.objects.get(pk=pk)
    if request.method == 'GET':
        form = RecipeForm(instance=recipe)
        return render(request, 'edit.html', {'form': form})
    else:
        form = RecipeForm(request.POST, instance=recipe)
        if form.is_valid():
            form.save()
            return redirect('home')
        else:
            return render(request, 'edit.html', {'form': form})


def delete_recipe(request, pk):
    recipe = Recipe.objects.get(pk=pk)
    if request.method == 'GET':
        form = DeleteRecipeForm(instance=recipe)
        return render(request, 'delete.html', {'form': form})
    else:
        recipe.delete()
        return redirect('home')


def recipe_details(request, pk):
    recipe = Recipe.objects.get(pk=pk)
    ingredients = recipe.ingredients.split(', ')
    return render(request, 'details.html', {'recipe': recipe, 'ingredients': ingredients})

Mock-exams/04-Mock-exam/recipes/templates/create.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/style.css">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="/static/images/chef.png" alt="chef">
        <li class="title"><a href="{% url 'home' %}">Recipes</a></li>
        <li><a href="{% url 'create recipe' %}">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Create Recipe</h1>
<div class="items-container">
    <div class="item">
        <form method="POST">
            {% csrf_token %}
            {{ form }}
{#            <label for="title">Title</label>#}
{#            <input type="text" name="title" maxlength="30" required="" id="id_title">#}
{#            <label for="imageURL">Image URL</label>#}
{#            <input type="url" name="image_url" maxlength="200" required="" id="id_image_url">#}
{#            <label for="description">Description</label>#}
{#            <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>#}
{#            <label for="ingredients">Ingredients</label>#}
{#            <input type="text" name="ingredients" maxlength="250" required="" id="id_ingredients">#}
{#            <label for="time">Time (Minutes)</label>#}
{#            <input type="number" name="time" required="" id="id_time">#}
            <input type="submit" value="Create">
        </form>
    </div>
</div>

    </div>


</body></html>

Mock-exams/04-Mock-exam/recipes/templates/delete.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/style.css">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="/static/images/chef.png" alt="chef">
        <li class="title"><a href="{% url 'home' %}">Recipes</a></li>
        <li><a href="{% url 'create recipe' %}">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Delete Recipe</h1>
<div class="items-container">
    <div class="item">
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" class="button delete" value="Delete">
        </form>
    </div>
</div>

    </div>


</body></html>

Mock-exams/04-Mock-exam/recipes/templates/details.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/style.css">
    <title>Recipes</title>
</head>

<body>

<nav>
    <ul>
        <img src="/static/images/chef.png" alt="chef">
        <li class="title"><a href="{% url 'home' %}">Recipes</a></li>
        <li><a href="{% url 'create recipe' %}">Add Recipe</a></li>
    </ul>
</nav>
<div class="container">

    <h1>Recipe Details</h1>
    <div class="items-container">
        <div class="item">
            <h2>{{ recipe.title }}</h2>
            <img class="detail-img" src="{{ recipe.image_url }}" alt="recipe-image">
            <div class="time">
                <img src="/static/images/clock.png">
                <p>{{ recipe.time }}min</p>
            </div>
            <h3>Ingredients</h3>
            <ul>
                {% for ingredient in ingredients %}
                    <li>{{ ingredient }}</li>
                {% endfor %}
            </ul>
            <h3>How to prepare?</h3>
            <div class="recipe-info-full">{{ recipe.description }}</div>
            <div class="buttons-container">
                <a class="button edit" href="{% url 'edit recipe' recipe.id %}">Edit</a>
                <a class="button delete" href="{% url 'delete recipe' recipe.id %}">Delete</a>
            </div>
        </div>
    </div>

</div>


</body>
</html>

Mock-exams/04-Mock-exam/recipes/templates/edit.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/style.css">
    <title>Recipes</title>
</head>

<body>

<nav>
    <ul>
        <img src="/static/images/chef.png" alt="chef">
        <li class="title"><a href="{% url 'home' %}">Recipes</a></li>
        <li><a href="{% url 'create recipe' %}">Add Recipe</a></li>
    </ul>
</nav>
<div class="container">

    <h1>Edit Recipe</h1>
    <div class="items-container">
        <div class="item">
            <form method="POST">
                {% csrf_token %}
                {{ form }}
                <input type="submit" class="button edit" value="Edit">
            </form>
        </div>
    </div>

</div>


</body>
</html>

Mock-exams/04-Mock-exam/recipes/templates/index.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/style.css">
    <title>Recipes</title>
</head>

<body>

<nav>
    <ul>
        <img src="/static/images/chef.png" alt="chef">
        <li class="title"><a href="{% url 'home' %}">Recipes</a></li>
        <li><a href="{% url 'create recipe' %}">Add Recipe</a></li>
    </ul>
</nav>
<div class="container">

    <h1>My Recipes</h1>
    {% if not recipes %}
        <h2>There are no recipes.</h2>
    {% else %}
        <div class="items-container">
        {% for recipe in recipes %}
            <div class="item">
                <h2>{{ recipe.title }}</h2>
                <img class="detail-img" src="{{ recipe.image_url }}" alt="recipe-image">
                <div class="recipe-info">{{ recipe.description }}</div>
                <div class="buttons-container">
                    <a class="button detail" href="{% url 'recipe details' recipe.id %}">Details</a>
                    <a class="button edit" href="{% url 'edit recipe' recipe.id %}">Edit</a>
                    <a class="button delete" href="{% url 'delete recipe' recipe.id %}">Delete</a>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    </div>
</div>


</body>

</html>